### ISSUE TITLE
No module named 'torchrl'

### ISSUE THREAD

**Issue by markingle** [Sourish07/Super-Mario-Bros-RL#3]
torchrl is not installing because version 0.1.1 is no longer available.  I installed version 2.0.0 and it breaks the code.....is there any chance you will be upgrading the code to support 2.0.0?

**Comment by Sourish07** [comment]
@markingle Hi, thanks for pointing this out. Could you please clone the `dev` branch and test out the new `requirements.txt` file? I've also updated the README.

**Comment by markingle** [comment]
Thank you for taking the time to correct the issue!  I can understand your code very well.  I am just now beginning my journey to learn AI....your project is very helpful.  Thank you!

**Comment by Sourish07** [comment]
@markingle Thank you for checking my project out! Good luck on your AI journey and I'm honored that my video is a part of it :)
